// Generated by CoffeeScript 1.6.2
define(['ovivo'], function() {
  return {
    _gettersNames: ['date', 'disabled', 'month', 'week_number', 'year', 'dateObj'],
    addResourceNeed: function(model) {
      var _view;

      _view = model.getView();
      return this.view.addResourceNeed(_view, model);
    },
    removeResourceNeed: function(model) {
      return this.view.removeResourceNeed(model);
    },
    checkToday: function() {
      var _now;

      if (this.collection.todayFound !== true) {
        _now = Date.today();
        if ((_now - this.dateObj()) === 0) {
          this.view.setToday();
          return this.collection.todayFound = true;
        }
      }
    },
    highlight: function(model) {
      return this.view.highlight(model);
    },
    removeHighlight: function(model) {
      return this.view.removeHighlight(model);
    },
    initialize: function(attrs, options) {
      this.proxyCall('initialize', arguments);
      this.set('pk', "" + (this.year()) + "-" + (this.month()) + "-" + (this.date()) + (this.disabled() === true ? '-disabled' : ''));
      this.set('dateObj', new Date(this.year(), this.month(), this.date()));
      this.view = new this.View({
        model: this,
        el: options.el
      });
      this.checkToday();
      return true;
    }
  };
});
