// Generated by CoffeeScript 1.6.2
define(['ovivo'], function() {
  return {
    _gettersNames: ['date', 'disabled', 'month', 'week_number', 'year', 'dateObj'],
    addEvent: function(model) {
      var _view;

      _view = model.getView();
      return this.view.addEvent(_view, model);
    },
    removeEvent: function(model) {
      return this.view.removeEvent(model);
    },
    addWorkingHour: function(model) {
      var _view;

      _view = model.getView();
      return this.view.addWorkingHour(_view, model);
    },
    removeWorkingHour: function(model) {
      return this.view.removeWorkingHour(model);
    },
    addInactivity: function(model) {
      var _view;

      _view = model.getView();
      return this.view.addInactivity(_view, model);
    },
    removeInactivity: function(model) {
      return this.view.removeInactivity(model);
    },
    initialize: function(attrs, options) {
      var _this = this;

      this.proxyCall('initialize', arguments);
      this.set('pk', "" + (this.year()) + "-" + (this.month()) + "-" + (this.date()) + (this.disabled() === true ? '-disabled' : ''));
      this.set('dateObj', new Date(this.year(), this.month(), this.date()));
      this.view = new this.View({
        model: this,
        el: options.el
      });
      _.each(ovivo.desktop.resources.events.dateCache["" + (this.year()) + "-" + (this.month() + 1) + "-" + (this.date())], function(event) {
        return _this.addEvent(event);
      });
      return true;
    }
  };
});
