// Generated by CoffeeScript 1.6.2
define(['ovivo'], function() {
  return {
    firstDate: function() {
      return this._firstDate;
    },
    show: function() {
      return this.view.show();
    },
    hide: function() {
      return this.view.hide();
    },
    initDays: function() {
      return this.collection.days.initElements(this.view.dayElements, this.days);
    },
    removeLoading: function() {
      return this.view.removeLoading();
    },
    _initialize: function(attrs, options) {
      this.on('rendered', this.initDays, this);
      return true;
    }
  };
});
