// Generated by CoffeeScript 1.6.2
define(['views/popups/Popup', 'ovivo'], function(Popup) {
  return Popup.extend({
    el: '.popup-create-new',
    events: _.extend({}, Popup.prototype.events, {
      'click .button-create-time': 'createTime',
      'click .button-create-timeoff': 'createTimeoff'
    }),
    createTime: function() {
      ovivo.desktop.pages.settings.show();
      ovivo.desktop.pages.settings.view.showSubView('availability');
      ovivo.desktop.popups.editPopupWorkingHour.createNew();
      this.close();
      return ovivo.desktop.popups.editPopupWorkingHour.show();
    },
    createTimeoff: function() {
      ovivo.desktop.pages.settings.show();
      ovivo.desktop.pages.settings.view.showSubView('timeoff');
      ovivo.desktop.popups.editPopupTimeoff.createNew();
      this.close();
      return ovivo.desktop.popups.editPopupTimeoff.show();
    },
    initialize: function() {
      this._initialize();
      return true;
    }
  });
});
