// Generated by CoffeeScript 1.6.2
define(['views/popups/EditPopup', '_features/trailZero', 'ovivo'], function(EditPopup, trailZero) {
  return EditPopup.extend({
    el: '.popup-resource-need',
    fields: ['start_time', 'end_time', 'start_date', 'end_date', 'repeat', 'employee_type', 'skill', 'num_employees', 'groups'],
    skillsTemplate: Handlebars.templates['skills'],
    groupsTemplate: Handlebars.templates['groups'],
    groupsProcessor: function(value) {
      return _.map(value, function(group) {
        return parseInt(group);
      });
    },
    types: function() {
      return {
        'start_time': String,
        'end_time': String,
        'start_date': String,
        'end_date': String,
        'repeat': Number,
        'employee_type': String,
        'skill': Number,
        'num_employees': Number,
        'groups': this.groupsProcessor
      };
    },
    skills: function() {
      return ovivo.desktop.resources.skills.map(function(skill) {
        return skill;
      });
    },
    createNew: function() {
      var _end, _now, _ref, _ref1, _start;

      _now = Date.today();
      _now.moveToFirstDayOfMonth();
      _start = new Date(_now);
      _now.moveToLastDayOfMonth();
      _end = new Date(_now);
      this.setModel(new this.collection.model({
        start_date: "" + (_start.getFullYear()) + "-" + (trailZero(_start.getMonth() + 1)) + "-" + (trailZero(_start.getDate())),
        end_date: "" + (_end.getFullYear()) + "-" + (trailZero(_end.getMonth() + 1)) + "-" + (trailZero(_end.getDate())),
        start_time: '09:00',
        end_time: '17:00',
        employee_type: 'fulltime',
        num_employees: 1,
        repeat: 1,
        weekdays: '1,2,3,4,5,6,7',
        skill: (_ref = ovivo.desktop.resources.skills.at(0)) != null ? _ref.pk() : void 0,
        groups: [(_ref1 = ovivo.desktop.resources.groups.at(0)) != null ? _ref1.pk() : void 0]
      }));
      return this.initEditMode();
    },
    processSkills: function() {
      return this.$('.property-value-skill').append($(this.skillsTemplate(this)).children());
    },
    processGroups: function() {
      return this.$('.property-value-groups').append($(this.groupsTemplate({
        tree: ovivo.desktop.resources.groups.tree
      })).children());
    },
    initialize: function() {
      this.types = this.types();
      this.collection = ovivo.desktop.resources.resourceNeeds;
      this.$('.datepicker').pickadate({
        format: 'yyyy-mm-dd',
        formatSubmit: 'yyyy-mm-dd',
        firstDay: 1
      });
      this._initialize();
      ovivo.desktop.resources.skills.def.then(_.bind(this.processSkills, this));
      ovivo.desktop.resources.groups.on('tree-ready', this.processGroups, this);
      return true;
    }
  });
});
