// Generated by CoffeeScript 1.6.2
define(['ovivo'], function() {
  return Backbone.View.extend({
    events: {
      'change .property-value': 'changeProperty',
      'click .close': 'close'
    },
    propertyRegExp: /\bproperty-value-(.+)\b/,
    changeProperty: function(e) {
      var _input, _name;

      _input = $(e.target).closest('.property-value');
      _name = this.propertyRegExp.exec(_input[0].className)[1];
      return this.model.set(_name, eval(_input.val()));
    },
    close: function() {
      return this.hide();
    },
    setModel: function(model) {
      var _this = this;

      this.model = model;
      return _.each(this.fields, function(field) {
        return _this.$('.property-value-' + field).val(model[field]().toString());
      });
    },
    show: function() {
      this.$el.show();
      return $('.popup-overlay').show();
    },
    hide: function() {
      this.$el.hide();
      return $('.popup-overlay').hide();
    },
    _initialize: function() {
      return true;
    }
  });
});
