// Generated by CoffeeScript 1.6.2
define(['views/popups/EditPopup', '_features/trailZero', 'ovivo'], function(EditPopup, trailZero) {
  return EditPopup.extend({
    el: '.popup-working-hour',
    fields: ['start_time', 'end_time', 'available', 'start_date', 'end_date', 'repeat'],
    types: {
      'start_time': String,
      'end_time': String,
      'available': eval,
      'start_date': String,
      'end_date': String,
      'repeat': eval
    },
    createNew: function() {
      var _end, _now, _start;

      _now = Date.today();
      _now.moveToFirstDayOfMonth();
      _start = new Date(_now);
      _now.moveToLastDayOfMonth();
      _end = new Date(_now);
      this.setModel(new this.collection.model({
        start_date: "" + (_start.getFullYear()) + "-" + (trailZero(_start.getMonth())) + "-" + (trailZero(_start.getDate())),
        end_date: "" + (_end.getFullYear()) + "-" + (trailZero(_end.getMonth())) + "-" + (trailZero(_end.getDate())),
        start_time: '09:00',
        end_time: '17:00',
        available: true,
        repeat: 1,
        weekdays: '0,1,2,3,4,5,6'
      }));
      return this.$('.button-add').show();
    },
    initialize: function() {
      this.collection = ovivo.desktop.resources.workingHours;
      this.$('.datepicker').pickadate({
        format: 'yyyy-mm-dd',
        formatSubmit: 'yyyy-mm-dd',
        firstDay: 1
      });
      this._initialize();
      return true;
    }
  });
});
