// Generated by CoffeeScript 1.6.2
define(['views/popups/EditPopup', 'ovivo'], function(EditPopup) {
  return EditPopup.extend({
    el: '.popup-timeoff',
    fields: ['start_date', 'end_date', 'reason'],
    intialize: function() {
      this._intialize();
      return true;
    }
  });
});
