// Generated by CoffeeScript 1.6.2
define(['views/popups/EditPopup', 'ovivo'], function(EditPopup) {
  return EditPopup.extend({
    el: '.popup-working-hour',
    fields: ['start_time', 'end_time', 'available', 'start_date', 'end_date', 'repeat'],
    intialize: function() {
      this._intialize();
      return true;
    }
  });
});
