// Generated by CoffeeScript 1.6.2
define(['views/popups/EditPopup', '_features/trailZero', 'ovivo'], function(EditPopup, trailZero) {
  return EditPopup.extend({
    el: '.popup-template',
    fields: ['name', 'repeat', 'resource_needs'],
    types: function() {
      return {
        'name': String,
        'repeat': Number,
        'resource_needs': String
      };
    },
    createNew: function() {
      this.setModel(new this.collection.model({
        name: '',
        repeat: 1,
        resource_needs: []
      }));
      return this.initEditMode();
    },
    initialize: function() {
      this.types = this.types();
      this.collection = ovivo.desktop.resources.templates;
      this._initialize();
      return true;
    }
  });
});
