// Generated by CoffeeScript 1.6.2
define(['ovivo'], function() {
  return Backbone.View.extend({
    events: {
      'click .close': 'close'
    },
    close: function() {
      return this.hide();
    },
    show: function() {
      this.$el.show();
      return $('.popup-overlay').show();
    },
    hide: function() {
      this.$el.hide();
      return $('.popup-overlay').hide();
    },
    _initialize: function() {
      return true;
    }
  });
});
