// Generated by CoffeeScript 1.6.2
define(['views/resources/ResourceBase', 'ovivo'], function(ResourceBase) {
  return ResourceBase.extend({
    common: {},
    tagName: 'li',
    template: Handlebars.templates['calendarMonth'],
    groupTemplate: Handlebars.templates['calendarMonth_group'],
    events: {},
    show: function() {
      return this.$el.removeClass('hide');
    },
    hide: function() {
      return this.$el.addClass('hide');
    },
    month: function() {
      return ovivo.config.MONTHS[this.model.month()];
    },
    rows: function() {
      return _.map(this.model.weeks, function(week) {
        return {
          cells: week
        };
      });
    },
    postRender: function() {
      this.dayElements = this.$('.days-container .week-row > td');
      return this.hide();
    },
    initialize: function() {
      this.proxyCall('initialize', arguments);
      return true;
    }
  });
});
