// Generated by CoffeeScript 1.6.2
define(['views/resources/ResourceBase', 'ovivo'], function(ResourceBase) {
  return ResourceBase.extend({
    common: {},
    tagName: 'li',
    className: 'resource-block',
    template: Handlebars.templates['resourceBlock'],
    groupTemplate: Handlebars.templates['resourceBlock_group'],
    events: {
      'click': 'processClick'
    },
    processClick: function() {
      return true;
    },
    _getTimeObj: function(field) {
      var _hours, _minutes, _obj, _ref, _ref1;

      _obj = new Date(Date.parse(this.date()));
      _ref = this[field]().split(':'), _hours = _ref[0], _minutes = _ref[1];
      _ref1 = [parseInt(_hours), parseInt(_minutes)], _hours = _ref1[0], _minutes = _ref1[1];
      _obj.setHours(_hours);
      return _obj.setMinutes(_minutes);
    },
    adjustPosition: function(start, range, height) {
      var _end, _scale, _start;

      _start = this._getTimeObj('start_time');
      _end = this._getTimeObj('end_time');
      _scale = height / range;
      if (_end < _start) {
        _end.setDate(_end.getDate() + 1);
      }
      return this.$el.css({
        'height': "" + (Math.floor((_end - _start) * _scale)) + "px",
        'top': "" + (Math.floor((_start - start) * _scale)) + "px"
      });
    },
    initialize: function() {
      this.proxyCall('initialize', arguments);
      return true;
    }
  });
});
