// Generated by CoffeeScript 1.6.2
define(['ovivo'], function() {
  return Backbone.View.extend({
    el: '.side-bar',
    events: {
      'click .menu-item': 'processItemClick'
    },
    menuItemRegExp: /^menu-item-(.*)$/,
    processItemClick: function(e) {
      var _item;

      _item = $(e.target).closest('.menu-item');
      ovivo.desktop.pages[this.menuItemRegExp.exec(_item[0].id)[1]].show();
      if (this.prev != null) {
        this.prev.removeClass('selected');
      } else {
        this.$('.selected').removeClass('selected');
      }
      _item.addClass('selected');
      this.prev = _item;
      return true;
    },
    initialize: function() {
      return true;
    }
  });
});
