// Generated by CoffeeScript 1.6.2
define(['ovivo'], function() {
  return Backbone.View.extend({
    el: '#voice-recognition',
    processKey: function(e) {
      if (!((e.ctrlKey === true) && (e.shiftKey === true) && (e.keyCode === 19))) {
        return;
      }
      this.model.set('show', true);
      return this.model.set('processing', true);
    },
    changeShow: function() {
      if (this.model.show() === true) {
        this.$el.addClass('show');
      } else {
        this.$el.removeClass('show');
      }
      return true;
    },
    initialize: function() {
      $(window).on('keypress', _.bind(this.processKey, this));
      this.model.on('change:show', this.changeShow, this);
      return true;
    }
  });
});
