// Generated by CoffeeScript 1.6.2
define(['models/resources/ResourceBase', 'views/period/GroupFilter', 'ovivo'], function(ResourceBase, View) {
  return ResourceBase.extend({
    _gettersNames: [['pk', 'root'], ['name', 'root']],
    initialize: function(attrs, options) {
      this.View = View;
      this.proxyCall('initialize', arguments);
      return true;
    }
  });
});
