// Generated by CoffeeScript 1.6.2
define(['models/period/Block', 'ovivo'], function(Block) {
  return Block.extend({
    idAttribute: 'cid',
    _gettersNames: ['date', 'workingHour', ['start_time', 'workingHour'], ['end_time', 'workingHour'], ['skills', 'workingHour'], ['groups', 'workingHour'], ['pk', 'workingHour'], ['startValue', 'workingHour'], ['endValue', 'workingHour'], ['user', 'workingHour']],
    initialize: function() {
      var _this = this;

      this.proxyCall('initialize', arguments);
      this.groupsHash = this.workingHour().groupsHash;
      ovivo.desktop.resources.users.def.done(function() {
        return _this.skillsHash = _this.workingHour().skillsHash;
      });
      return true;
    }
  });
});
