// Generated by CoffeeScript 1.6.2
define(['collections/period/SkillGroups', 'ovivo'], function(SkillGroups) {
  return {
    addBlock: function(block) {
      var _key, _skillGroup;

      _key = block.skill();
      _skillGroup = this.skillGroups.get(_key);
      if (_skillGroup == null) {
        _skillGroup = this.skillGroups.addModel({
          pk: _key,
          group: block.group()
        });
      }
      return _skillGroup.addBlock(block);
    },
    _removeBlockPartial: function(block) {
      var _key, _ref, _skillGroup;

      if (((_ref = block.resourceNeed().changed) != null ? _ref.skill : void 0) != null) {
        _key = block.resourceNeed().previous('skill');
      } else {
        _key = block.skill();
      }
      _skillGroup = this.skillGroups.get(_key);
      if (_skillGroup != null) {
        return _skillGroup.removeBlock(block);
      }
    },
    initialize: function() {
      return this.skillGroups = new SkillGroups();
    }
  };
});
