// Generated by CoffeeScript 1.6.2
define(['models/resources/ResourceBase', 'collections/period/ResourceNeedTimeGroups', 'views/period/PeriodGroup', 'ovivo'], function(ResourceBase, TimeGroups, View) {
  return ResourceBase.extend({
    _gettersNames: ['pk'],
    clearScroll: function() {
      return this.view.clearScroll();
    },
    processScroll: function(obj, val) {
      return this.view.processScroll(obj, val);
    },
    addBlock: function(block) {
      var _key, _timeGroup;

      _key = ("" + (block.start_time()) + "-" + (block.end_time())).replace(/\:/g, '-');
      _timeGroup = this.timeGroups.get(_key);
      if (_timeGroup == null) {
        _timeGroup = this.timeGroups.addModel({
          pk: _key,
          start_time: block.start_time(),
          end_time: block.end_time()
        });
      }
      _timeGroup.addBlock(block);
      return this._blocksCounter += 1;
    },
    removeBlock: function(block) {
      var _timeGroup;

      _timeGroup = block.timeGroup;
      if (_timeGroup != null) {
        _timeGroup.removeBlock(block);
      }
      this._blocksCounter -= 1;
      if (this._blocksCounter === 0) {
        return this.collection.remove(this);
      }
    },
    initialize: function(attrs, options) {
      this.View = View;
      this.timeGroups = new TimeGroups();
      this.timeGroups.periodGroup = this;
      this._blocksCounter = 0;
      this.proxyCall('initialize', arguments);
      return true;
    }
  });
});
