// Generated by CoffeeScript 1.6.2
define(['views/pages/PageBase', '_features/Switcher', '_features/facebook', 'ovivo'], function(PageBase, Switcher, facebook) {
  return PageBase.extend({
    el: '.page.page-settings .connections-view',
    name: 'connections',
    events: {},
    keys: ['facebook'],
    types: [0],
    variants: [[true, false]],
    _valueHandlerCreator: function(key, processor) {
      var _func;

      _func = function(value) {
        return processor._set('status', value);
      };
      return _.bind(_func, this);
    },
    _valueHandlerSetCreator: function(key) {
      var _func;

      _func = function(value) {
        return this.switchers[key].setValue(value);
      };
      return _.bind(_func, this);
    },
    initialize: function() {
      var _this = this;

      this.switchers = {};
      _.each(this.keys, function(key, i) {
        var _processor, _switcher;

        _switcher = _this.switchers[key] = new Switcher(_this.$('.options-' + key), _this.variants[_this.types[i]]);
        _processor = eval(key);
        _processor.initialize();
        _processor.on('change:status', _this._valueHandlerSetCreator(key));
        return _switcher.on('value', _this._valueHandlerCreator(key, _processor));
      });
      return true;
    }
  });
});
