// Generated by CoffeeScript 1.6.2
define(['views/pages/PageBase', '_features/Switcher', 'ovivo'], function(PageBase, Switcher) {
  return PageBase.extend({
    el: '.page.page-settings .notifications-view',
    name: 'notifications',
    events: {},
    keys: ['notify_email', 'notify_sms', 'activity_digest', 'response_confirmation', 'event_reminders', 'event_urgent_within'],
    types: [0, 0, 0, 0, 0, 1],
    variants: [[true, false], [3, 7, 14]],
    _valueHandlerCreator: function(key) {
      return function(value) {
        return ovivo.desktop.resources.communication.set(key, value);
      };
    },
    setValues: function() {
      var _this = this;

      return _.each(this.keys, function(key, i) {
        var _switcher;

        _switcher = _this.switchers[key];
        return _switcher.setValue(ovivo.desktop.resources.communication[key]());
      });
    },
    initialize: function() {
      var _this = this;

      this.switchers = {};
      _.each(this.keys, function(key, i) {
        var _switcher;

        _switcher = _this.switchers[key] = new Switcher(_this.$('.options-' + key), _this.variants[_this.types[i]]);
        return _switcher.on('value', _this._valueHandlerCreator(key));
      });
      ovivo.desktop.resources.communication.def.done(_.bind(this.setValues, this));
      ovivo.desktop.resources.communication.on('sync', this.setValues, this);
      return true;
    }
  });
});
