// Generated by CoffeeScript 1.6.2
define(['views/pages/PageBase', 'views/pages/Settings/General', 'views/pages/Settings/Notifications', 'views/pages/Settings/Availability', 'views/pages/Settings/Connections', 'ovivo'], function(PageBase, GeneralView, NotificationsView, AvailabilityView, ConnectionsView) {
  return PageBase.extend({
    el: '.page.page-settings',
    events: function() {
      return _.extend({}, PageBase.prototype.events, {});
    },
    transitionStart: function() {
      this.proxyCall('transitionStart', arguments);
      return true;
    },
    transitionComplete: function() {
      this.proxyCall('transitionComplete', arguments);
      return true;
    },
    initialize: function() {
      this.SubViews = [GeneralView, NotificationsView, AvailabilityView, ConnectionsView];
      this.defaultSubView = 'general';
      this.proxyCall('initialize', arguments);
      return true;
    }
  });
});
