// Generated by CoffeeScript 1.6.2
define(['views/pages/PageBase', 'ovivo'], function(PageBase) {
  return PageBase.extend({
    el: '.page.page-settings .resource-need-view',
    name: 'resourceNeed',
    events: {
      'click .button-add-new': 'addNew'
    },
    addNew: function() {
      ovivo.desktop.popups.editPopupResourceNeed.show();
      ovivo.desktop.popups.editPopupResourceNeed.createNew();
      return true;
    },
    addResourceNeed: function(resourceNeed) {
      return this.resourceNeeds.append(resourceNeed.editView.el);
    },
    initialize: function() {
      this.resourceNeeds = this.$('.resource-needs');
      ovivo.desktop.resources.resourceNeeds.on('add', this.addResourceNeed, this);
      return true;
    }
  });
});
