// Generated by CoffeeScript 1.6.2
define(['views/pages/PageBase', 'ovivo'], function(PageBase) {
  return PageBase.extend({
    el: '.page.page-settings .timeoff-view',
    name: 'timeoff',
    events: {},
    initialize: function() {
      return true;
    }
  });
});
