// Generated by CoffeeScript 1.6.2
define(['models/resources/ResourceBase', 'ovivo-ella'], function(ResourceBase, View) {
  return ResourceBase.extend({
    _gettersNames: ['checked', 'parent', 'children', 'primary_department', 'pk'],
    initialize: function(attrs, options) {
      this.set('children', []);
      this.proxyCall('initialize', arguments);
      return true;
    }
  });
});
