// Generated by CoffeeScript 1.6.2
define(['models/resources/ResourceBase', 'views/resources/Inactivity', 'ovivo'], function(ResourceBase, View) {
  return ResourceBase.extend({
    _gettersNames: ['start', 'end', 'reason', 'approved', 'municipality', 'type', 'pk'],
    validate: function(attrs) {
      if ((attrs.start != null) && (attrs.end != null) && (attrs.municipality != null)) {
        return void 0;
      } else {
        return gettext('Params are missing');
      }
    },
    processChange: function() {
      if (this.id != null) {
        return this.save();
      }
    },
    initialize: function(attrs, options) {
      this.View = View;
      this.on('change', this.processChange, this);
      this.proxyCall('initialize', arguments);
      return true;
    }
  });
});
