// Generated by CoffeeScript 1.6.2
define(['models/resources/ResourceBase', 'views/resources/Period', 'ovivo'], function(ResourceBase, View) {
  return ResourceBase.extend({
    typeName: 'period',
    localStorageOnly: true,
    _gettersNames: ['pk', 'start_date', 'end_date', 'templates', 'primary_department', 'groups'],
    initialize: function(attrs, options) {
      this.View = View;
      this.proxyCall('initialize', arguments);
      return true;
    }
  });
});
