// Generated by CoffeeScript 1.6.2
define(['_common/ToolsBase', 'ovivo'], function(ToolsBase) {
  var _Base;

  _Base = Backbone.Model.extend(_.extend({}, ToolsBase, {
    idAttribute: 'pk',
    createGetters: ToolsBase.once('createGetters', function() {
      var _this = this;

      return _.each(this._gettersNames, function(name) {
        if (_this.constructor.prototype[name] == null) {
          return _this.constructor.prototype[name] = function() {
            return this.get(name);
          };
        }
      });
    }),
    initialize: function(attrs, options) {
      this.createGetters();
      if (this.View != null) {
        this.view = new this.View({
          model: this
        });
      }
      return true;
    },
    setValue: function(name, value) {
      return this.set(name, value);
    }
  }));
  _Base.prototype._base = _Base;
  return _Base;
});
