// Generated by CoffeeScript 1.6.2
define(['models/resources/ResourceBase', 'ovivo'], function(ResourceBase) {
  return ResourceBase.extend({
    typeName: 'template',
    _gettersNames: ['pk', 'name', 'repeat', 'resource_needs'],
    initialize: function(attrs, options) {
      this.proxyCall('initialize', arguments);
      return true;
    }
  });
});
