// Generated by CoffeeScript 1.6.2
define(['models/resources/ResourceBase', 'views/resources/Template', 'ovivo'], function(ResourceBase, View) {
  return ResourceBase.extend({
    typeName: 'template',
    localStorageOnly: true,
    _gettersNames: ['pk', 'name', 'repeat', 'resource_needs', 'primary_department'],
    changePD: function() {
      return this.set('resource_needs', []);
    },
    resourceNeedsChange: function() {
      var _cur, _new, _prev, _removed,
        _this = this;

      if (this.id == null) {
        return true;
      }
      _cur = this.resource_needs();
      _prev = this.previous('resource_needs');
      _removed = _.without.apply(_, [_prev].concat(_cur));
      _new = _.without.apply(_, [_cur].concat(_prev));
      _.each(_removed, function(id) {
        return ovivo.desktop.resources.resourceNeeds.get(id).removeTemplate(_this.id);
      });
      return _.each(_new, function(id) {
        return ovivo.desktop.resources.resourceNeeds.get(id).addTemplate(_this.id);
      });
    },
    removeResourceNeed: function(id) {
      var _arr, _i, _val;

      _val = [];
      _arr = this.resource_needs();
      _.each(_arr, function(el) {
        return _val.push(el);
      });
      _i = _val.indexOf(id);
      if (_i !== -1) {
        _val.splice(_i, 1);
      }
      return this.set('resource_needs', _val);
    },
    initialize: function(attrs, options) {
      this.View = View;
      this.on('change:primary_department', this.changePD, this);
      this.on('change:resource_needs', this.resourceNeedsChange, this);
      this.proxyCall('initialize', arguments);
      return true;
    }
  });
});
