// Generated by CoffeeScript 1.6.2
define(['models/resources/ResourceBase', 'views/resources/WorkingHour', 'ovivo'], function(ResourceBase, View) {
  return ResourceBase.extend({
    _gettersNames: ['weekdays', 'available', 'repeat', 'exclusions', 'groups', 'start_date', 'end_date', 'start_time', 'end_time', 'pk', 'start_date_obj', 'end_date_obj'],
    _getTrueHash: function(hash) {
      return _.compact(_.map(_.pairs(hash), function(arr) {
        if (arr[1] === true) {
          return arr[0];
        } else {
          return void 0;
        }
      }));
    },
    processWeek: function(num, value) {
      var _weeks;

      value = !value;
      this.weekdaysHash[num] = value;
      _weeks = this._getTrueHash(this.weekdaysHash);
      this.set('weekdays', _weeks.length > 0 ? _weeks.join(',') : null);
      return true;
    },
    processGroup: function(pk, value) {
      var _groups;

      value = !value;
      this.groupsHash[pk] = value;
      _groups = this._getTrueHash(this.groupsHash);
      this.set('groups', _.map(_groups, function(group) {
        return parseInt(group);
      }));
      return true;
    },
    groups: function() {
      var _groups;

      if ((_groups = this.get('groups')) != null) {
        return _groups;
      } else {
        return [];
      }
    },
    validate: function(attrs) {
      if ((attrs.available != null) && (attrs.start_date != null) && (attrs.start_time != null) && (attrs.end_time != null) && (attrs.weekdays != null) && attrs.repeat) {
        return void 0;
      } else {
        return gettext('Params are missing');
      }
    },
    processChange: function(model, obj) {
      if ((this.id != null) && (obj.socket_io !== true) && (obj.cache_update !== true)) {
        return this.save();
      }
    },
    toJSON: function() {
      var _json;

      _json = Backbone.Model.prototype.toJSON.call(this);
      if ((_json.groups instanceof Array) && (_json.groups.length === 0)) {
        this.set('groups', null, {
          silent: true
        });
        _json.groups = null;
      }
      delete _json.exclusions;
      return _json;
    },
    processRange: function(start, end) {
      var _arr, _day, _end, _i, _repeat, _start, _startWeek;

      _arr = [];
      _start = this.start_date_obj();
      _startWeek = _start.getWeek();
      _end = this.end_date_obj();
      _repeat = this.repeat();
      if (_start > start) {
        start = _start;
      }
      if ((_end != null) && (_end < end)) {
        end = _end;
      }
      _i = new Date(start);
      while (_i <= end) {
        _day = _i.getDay() - 1;
        if (_day < 0) {
          _day = 7 + _day;
        }
        if ((this.weekdaysHash[_day] === true) && ((_repeat === 1) || (((Math.floor(_i - _start) / 86400000 / 7) % _repeat) === 0))) {
          _arr.push({
            date: new Date(_i),
            model: this
          });
        }
        _i.setDate(_i.getDate() + 1);
      }
      return _arr;
    },
    getView: function() {
      return new this.View({
        model: this
      });
    },
    initialize: function(attrs, options) {
      var _end_date, _ref;

      this.View = View;
      this.proxyCall('initialize', arguments);
      this.set('start_date_obj', new Date(Date.parse(this.start_date())));
      if ((_end_date = this.end_date()) != null) {
        this.set('end_date_obj', new Date(Date.parse(_end_date)));
      }
      this.on('change', this.processChange, this);
      this.on('change:group', this.processChange, this);
      this.groupsHash = _.reduce(this.groups(), (function(memo, elem) {
        memo[elem] = true;
        return memo;
      }), {});
      this.weekdaysHash = _.reduce((_ref = this.weekdays()) != null ? _ref.split(',') : void 0, (function(memo, elem) {
        memo[elem] = true;
        return memo;
      }), {});
      return true;
    }
  });
});
