// Generated by CoffeeScript 1.6.2
define(['_features/dateFormatter', 'views/resources/ResourceBase', 'ovivo'], function(dateFormatter, ResourceBase) {
  return ResourceBase.extend({
    common: {},
    tagName: 'li',
    className: 'comment',
    template: Handlebars.templates['comment'],
    groupTemplate: Handlebars.templates['comment_group'],
    pub_date: function() {
      return dateFormatter(this.model.pub_date());
    },
    initialize: function() {
      this.proxyCall('initialize', arguments);
      return true;
    }
  });
});
