// Generated by CoffeeScript 1.6.2
define(['views/resources/ResourceBase', 'ovivo'], function(ResourceBase) {
  return ResourceBase.extend({
    common: {},
    tagName: 'li',
    className: 'period',
    template: Handlebars.templates['period'],
    groupTemplate: Handlebars.templates['period_group'],
    events: {
      'click': 'processClick'
    },
    _getDateStr: function(_date) {
      if (_date != null) {
        return "" + (_date.getDate()) + ". " + (ovivo.config.MONTHS[_date.getMonth()].toLowerCase().slice(0, 3));
      } else {
        return '';
      }
    },
    start_date: function() {
      return this._getDateStr(new Date(Date.parse(this.model.start_date())));
    },
    end_date: function() {
      return this._getDateStr(new Date(Date.parse(this.model.end_date())));
    },
    renderTemplates: function() {
      return this.$('.templates-list').html(_.map(this.templates(), function(id) {
        return ovivo.desktop.resources.templates.get(id).name();
      }).join(', '));
    },
    renderGroups: function() {
      return this.$('.groups-list').html(_.map(this.groups(), function(id) {
        return ovivo.desktop.resources.groups.get(id).name();
      }).join(', '));
    },
    postRender: function() {
      ovivo.desktop.resources.templates.def.done(_.bind(this.renderTemplates, this));
      return ovivo.desktop.resources.groups.def.done(_.bind(this.renderGroups, this));
    },
    processClick: function() {
      ovivo.desktop.popups.editPopupPeriod.show();
      return ovivo.desktop.popups.editPopupPeriod.setModel(this.model);
    },
    initialize: function() {
      this.proxyCall('initialize', arguments);
      return true;
    }
  });
});
