// Generated by CoffeeScript 1.6.2
define(['views/resources/ResourceBase', 'ovivo'], function(ResourceBase) {
  return ResourceBase.extend({
    common: {},
    tagName: 'li',
    className: 'resource-need element',
    template: Handlebars.templates['resourceNeed'],
    groupTemplate: Handlebars.templates['resourceNeed_group'],
    groupsTemplate: Handlebars.templates['groupsResourceNeed'],
    events: {
      'mouseenter': 'processMouseEnter',
      'mouseleave': 'processMouseLeave',
      'click': 'processClick'
    },
    processMouseEnter: function() {
      return this.model.highlight();
    },
    processMouseLeave: function() {
      return this.model.removeHighlight();
    },
    processClick: function() {
      ovivo.desktop.popups.editPopupResourceNeed.show();
      return ovivo.desktop.popups.editPopupResourceNeed.setModel(this.model);
    },
    _getDateStr: function(_date) {
      if (_date != null) {
        return "" + (ovivo.config.DAYS[_date.getDay()].toLowerCase().slice(0, 3)) + " " + (_date.getDate()) + ". " + (ovivo.config.MONTHS[_date.getMonth()].toLowerCase());
      } else {
        return '';
      }
    },
    start_date: function() {
      var _start_date;

      if ((_start_date = this.model.start_date()) != null) {
        return this._getDateStr(new Date(Date.parse(_start_date)));
      } else {
        return '';
      }
    },
    end_date: function() {
      var _end_date;

      if (this.model.end_date() === this.model.start_date()) {
        return '';
      } else if ((_end_date = this.model.end_date()) != null) {
        return " – " + (this._getDateStr(new Date(Date.parse(_end_date))));
      } else {
        return ' – \u221E';
      }
    },
    available: function() {
      if (this.model.available() === true) {
        return gettext('Available');
      } else {
        return gettext('Unavailable');
      }
    },
    groups: function() {
      return _.map(this.model.groups(), function(pk) {
        return ovivo.desktop.resources.groups.get(pk);
      });
    },
    renderGroups: function() {
      var _container;

      _container = this.$('ul.groups');
      return _container.append($(this.groupsTemplate(this)).children());
    },
    postRender: function() {
      return ovivo.desktop.resources.groups.def.done(_.bind(this.renderGroups, this));
    },
    _checkMatch: function(av_, need) {
      var end, start, _end, _start;

      _start = av_.startValue;
      _end = av_.endValue;
      start = need.startValue;
      end = need.endValue;
      return (_start >= start) && (_end <= end);
    },
    _addAvailability: function(model) {
      var _container, _el;

      _el = model.getView().el;
      _container = this.$('li.group-' + model.group() + ' ul.availabilities');
      return _container.append(_el);
    },
    addAvailability: function(model) {
      if ((this.model.groupsHash[model.group()] === true) && (this._checkMatch(model, this.model))) {
        return this.rendered.done(_.bind(_.wrap(model, this._addAvailability), this));
      }
    },
    initialize: function() {
      this.model.setDeltaHours();
      this.rendered = new $.Deferred();
      this.on('rendered', this._resolveDef(this.rendered));
      this.proxyCall('initialize', arguments);
      return true;
    }
  });
});
