// Generated by CoffeeScript 1.6.2
define(['views/resources/ResourceBase', 'ovivo'], function(ResourceBase) {
  return ResourceBase.extend({
    common: {},
    tagName: 'li',
    className: 'resource-need element',
    template: Handlebars.templates['resourceNeedEdit'],
    groupTemplate: Handlebars.templates['resourceNeedEdit_group'],
    events: {
      'click li.weekday': 'weekdayClick',
      'click .edit-button': 'edit',
      'click .remove-button': 'processRemove'
    },
    weekdayClick: function(e) {
      var _i, _item;

      _item = $(e.target).closest('.weekday');
      _i = _item.index();
      return this.model.processWeek(_i, this.model.weekdaysHash[_i]);
    },
    edit: function() {
      ovivo.desktop.popups.editPopupResourceNeed.show();
      return ovivo.desktop.popups.editPopupResourceNeed.setModel(this.model);
    },
    _getDateStr: function(_date) {
      if (_date != null) {
        return "" + (_date.getDate()) + ". " + (ovivo.config.MONTHS[_date.getMonth()].toLowerCase().slice(0, 3));
      } else {
        return '';
      }
    },
    renderSkill: function() {
      var _ref;

      return this.$('.skill-value').html((_ref = ovivo.desktop.resources.skills.get(this.model.skill())) != null ? _ref.name() : void 0);
    },
    postRender: function() {
      var _this = this;

      this.$('.columns.weekdays > li').each(function(i, elem) {
        if (_this.model.weekdaysHash[i] === true) {
          return $(elem).addClass('checked');
        } else {
          return $(elem).removeClass('checked');
        }
      });
      return ovivo.desktop.resources.skills.def.done(_.bind(this.renderSkill, this));
    },
    initialize: function() {
      this.proxyCall('initialize', arguments);
      this.weekDays = this.$('ul.weekdays');
      return true;
    }
  });
});
