// Generated by CoffeeScript 1.6.2
define(['views/pages/Calendar/DaysCollectorPage', 'views/pages/PageBase', 'collections/calendar/Weeks', 'ovivo'], function(DaysCollectorPage, PageBase, Weeks) {
  return PageBase.extend(_.extend({}, DaysCollectorPage, {
    el: '.page.page-calendar .week-view',
    name: 'week',
    Collectors: Weeks,
    events: {
      'scroll': 'processScroll'
    },
    processScroll: function() {
      if (this._scrollDataFlag === false) {
        this._offsetHeight = this.el.offsetHeight;
      }
      if (this.currentModel !== null) {
        this.currentModel.view.processScroll(this.el.scrollTop, this._offsetHeight);
      }
      return true;
    },
    _getKey: function(year, number) {
      return "" + year + "-" + number;
    },
    _getObj: function(year, number) {
      return {
        year: year,
        number: number
      };
    },
    _postNavigate: function() {
      return this.processScroll();
    },
    prev: function() {
      this.current.moveToDayOfWeek(4, -1);
      this.navigate(this.current.getFullYear(), this.current.getWeek());
      return this._postNavigate();
    },
    next: function() {
      this.current.moveToDayOfWeek(4, 1);
      this.navigate(this.current.getFullYear(), this.current.getWeek());
      return this._postNavigate();
    },
    today: function() {
      var _now;

      _now = Date.today();
      _now.setWeek(_now.getWeek());
      _now.moveToDayOfWeek(4);
      this.current = _now;
      this.navigate(_now.getFullYear(), _now.getWeek());
      return this._postNavigate();
    },
    _isToday: function(year, number) {
      var _now;

      _now = Date.today();
      _now.setWeek(_now.getWeek());
      _now.moveToDayOfWeek(4);
      return (_now.getFullYear() === year) && (_now.getWeek() === number);
    },
    processCollectorShow: function(collector) {
      var _this = this;

      this.values.week.html(collector.number());
      this.values.month.html(ovivo.config.MONTHS[collector.month()].slice(0, 3));
      this.values.year.html(collector.year());
      return _.each(collector.days, function(obj, i) {
        return _this.dates[i].innerHTML = "" + obj.date;
      });
    },
    processCollectorHide: function(month) {},
    processWindowResize: function() {
      return this._scrollDataFlag = false;
    },
    initialize: function() {
      var _now;

      this.current = _now = new Date.today();
      this._scrollDataFlag = false;
      $(window).on('resize', this.processWindowResize, this);
      _now.setWeek(_now.getWeek());
      _now.moveToDayOfWeek(4);
      this._initialize();
      this.title = $('.page.page-calendar header span.title.week-title');
      this.dates = $('.page.page-calendar header .weekdays-row span.date');
      this.collectorsList = this.$('.weeks-list');
      this.values = {
        week: $('.page.page-calendar header .week-banner .week-value'),
        month: $('.page.page-calendar header .week-banner .month-value'),
        year: $('.page.page-calendar header .week-banner .year-value')
      };
      this.todayButton = $('.page.page-calendar header .week-today');
      this.navigate(_now.getFullYear(), _now.getWeek());
      return true;
    }
  }));
});
