// Generated by CoffeeScript 1.6.2
define(['views/resources/ResourceBase', 'ovivo'], function(ResourceBase) {
  return ResourceBase.extend({
    common: {},
    tagName: 'li',
    className: 'group-filter',
    template: Handlebars.templates['groupFilter'],
    groupTemplate: Handlebars.templates['groupFilter_group'],
    events: {},
    postRender: function() {},
    initialize: function() {
      this.proxyCall('initialize', arguments);
      return true;
    }
  });
});
