// Generated by CoffeeScript 1.6.2
define(['views/resources/ResourceBase', 'ovivo'], function(ResourceBase) {
  return ResourceBase.extend({
    common: {},
    tagName: 'li',
    className: 'period-group',
    template: Handlebars.templates['periodGroup'],
    groupTemplate: Handlebars.templates['periodGroup_group'],
    preventChangeRender: true,
    pk: function() {
      return this.group();
    },
    events: {
      'click': 'processClick'
    },
    processClick: function() {},
    clearScroll: function() {},
    processScroll: function(obj, val) {},
    addBlock: function(block) {},
    _renderGroup: function() {
      return this.$('.group-name').html(ovivo.desktop.resources.groups.get(this.group()).name());
    },
    postRender: function() {
      ovivo.desktop.resources.groups.def.done(_.bind(this._renderGroup, this));
      return this.renderDef.resolve();
    },
    initialize: function() {
      this.renderDef = new $.Deferred();
      this.proxyCall('initialize', arguments);
      return true;
    }
  });
});
