// Generated by CoffeeScript 1.6.2
define(['views/resources/ResourceBase', '_common/ToolsBase', 'ovivo'], function(ResourceBase, ToolsBase) {
  return ResourceBase.extend({
    common: {},
    tagName: 'table',
    template: Handlebars.templates['periodBlockWeek'],
    groupTemplate: Handlebars.templates['periodBlockWeek_group'],
    events: {},
    initialize: function() {
      this.proxyCall('initialize', arguments);
      return true;
    }
  });
});
