// Generated by CoffeeScript 1.6.2
define(['views/resources/ResourceBase', '_common/ToolsBase', 'ovivo'], function(ResourceBase, ToolsBase) {
  return ResourceBase.extend({
    common: {},
    tagName: 'li',
    className: 'resource-need-row',
    template: Handlebars.templates['resourceNeedWeek'],
    groupTemplate: Handlebars.templates['resourceNeedWeek_group'],
    events: {},
    initialize: function() {
      this.proxyCall('initialize', arguments);
      return true;
    }
  });
});
