// Generated by CoffeeScript 1.6.2
define(['views/resources/ResourceBase', 'ovivo'], function(ResourceBase) {
  return ResourceBase.extend({
    common: {},
    tagName: 'li',
    className: 'time-group',
    template: Handlebars.templates['resourceNeedTimeGroup'],
    groupTemplate: Handlebars.templates['resourceNeedTimeGroup_group'],
    preventChangeRender: true,
    events: {
      'click': 'processClick'
    },
    processClick: function() {},
    clearScroll: function() {},
    processScroll: function(obj, val) {},
    addBlock: function(block) {},
    postRender: function() {
      var _this = this;

      this.resourceNeedWeeks = this.$('.resource-needs-rows');
      this.model.resourceNeedWeeks.each(function(rnw) {
        return _this.addResourcNeedWeek(rnw);
      });
      this.model.resourceNeedWeeks.on('add', this.addResourcNeedWeek, this);
      return this.renderDef.resolve();
    },
    addResourcNeedWeek: function(rnw) {
      return this.resourceNeedWeeks.append(rnw.view.el);
    },
    initialize: function() {
      this.renderDef = new $.Deferred();
      this.proxyCall('initialize', arguments);
      return true;
    }
  });
});
