// Generated by CoffeeScript 1.6.2
define(['views/resources/ResourceBase', 'views/period/GroupSectionBase', 'ovivo'], function(ResourceBase, GroupSectionBase) {
  return ResourceBase.extend(_.extend({}, GroupSectionBase, {
    common: {},
    MIN_BLOCK_HEIGHT: 100,
    tagName: 'li',
    className: 'skill-group',
    template: Handlebars.templates['skillGroup'],
    groupTemplate: Handlebars.templates['skillGroup_group'],
    preventChangeRender: true,
    events: {
      'click': 'processClick'
    },
    processClick: function() {},
    clearScroll: function() {
      this._clearHeader();
      this._clearFolding();
      return true;
    },
    processScroll: function(obj, val) {
      var _val;

      _val = Math.min(obj.height - this.MIN_BLOCK_HEIGHT, val);
      this._animateHeader(_val, val);
      if (obj.last === true) {
        return;
      }
      return this._animateFolding(_val, val);
    },
    addBlock: function(block) {},
    _renderSkill: function() {
      return this.$('.skill-name').html(ovivo.desktop.resources.skills.get(this.pk()).name());
    },
    postRender: function() {
      var _this = this;

      this.header = this.$('.day-blocks.header')[0];
      this.employeeRows = this.$('.employee-rows');
      ovivo.desktop.resources.skills.def.done(_.bind(this._renderSkill, this));
      this.addEmployeeRows(this.model.skillEmployeeRows.map(function(t) {
        return t;
      }));
      this.model.skillEmployeeRows.on('add', this.addEmployeeRows, this);
      return this.renderDef.resolve();
    },
    addEmployeeRows: function(employeeRows) {
      return this._addViewSorted(this.employeeRows, this.model.skillEmployeeRows, employeeRows);
    },
    initialize: function() {
      this.renderDef = new $.Deferred();
      this.proxyCall('initialize', arguments);
      return true;
    }
  }));
});
