// Generated by CoffeeScript 1.6.2
define(['views/resources/ResourceBase', 'views/period/GroupSectionBase', 'views/period/EventEmployee', 'ovivo'], function(ResourceBase, GroupSectionBase, EventEmployee) {
  return ResourceBase.extend(_.extend({}, GroupSectionBase, {
    common: {},
    MIN_BLOCK_HEIGHT: 100,
    tagName: 'table',
    className: 'day-blocks content employee-row',
    template: Handlebars.templates['employeeRowSkill'],
    groupTemplate: Handlebars.templates['employeeRowSkill_group'],
    preventChangeRender: true,
    events: {
      'click': 'processClick'
    },
    processClick: function() {},
    clearScroll: function() {},
    processScroll: function(obj, val) {},
    postRender: function() {
      this.eventContainers = this.$('td.day-block ul.activities');
      return this.renderDef.resolve();
    },
    addEvent: function(event, obj) {
      var _this = this;

      return this.renderDef.done(function() {
        var _view;

        _view = new EventEmployee({
          model: event
        }, obj);
        $(_this.eventContainers.get(event.day)).append(_view.el);
        return _view;
      });
    },
    initialize: function() {
      this.renderDef = new $.Deferred();
      this.proxyCall('initialize', arguments);
      return true;
    }
  }));
});
