// Generated by CoffeeScript 1.6.2
define(['_common/ToolsBase', 'ovivo'], function(ToolsBase) {
  var _Base;

  _Base = Backbone.View.extend(_.extend({}, ToolsBase, {
    show: function() {
      this.model.trigger.apply(this.model, ['show'].concat(Array.prototype.slice.call(arguments, 0)));
      return true;
    },
    showEl: function() {
      return this.$el.removeClass('hide');
    },
    hideEl: function() {
      return this.$el.addClass('hide');
    },
    transitionStart: function() {},
    transitionComplete: function(type) {
      if (type === 'exit') {
        this.hideEl();
      }
      return true;
    },
    initialize: function() {
      this.content = this.$('div.content')[0];
      return true;
    }
  }));
  _Base.prototype._base = _Base;
  return _Base;
});
