// Generated by CoffeeScript 1.6.2
define(['models/resources/GroupRelation', '_common/ResourceManagerBase', 'ovivo'], function(Model, ResourceManagerBase) {
  return Backbone.Collection.extend(_.extend({}, ResourceManagerBase, {
    model: Model,
    url: function() {
      return "" + ovivo.config.API_URL_PREFIX + "users/" + ovivo.config.USER_ID + "/groups/";
    },
    postProcess: (function() {
      var _processGroup;

      _processGroup = function(allowed, parent, group) {
        var _groupResource,
          _this = this;

        if (_.indexOf(allowed, group.id) !== -1) {
          _groupResource = this.get(group.id);
          _groupResource.set('parent', parent);
          _groupResource.set('primary_department', group.primary_department());
          if (parent !== null) {
            this.get(parent).get('children').push(_groupResource);
          }
          parent = group.id;
        }
        _.each(group.children(), function(pk) {
          return _processGroup.call(_this, allowed, parent, ovivo.desktop.resources.groups.get(pk));
        });
        return true;
      };
      return function() {
        var _allowed,
          _this = this;

        _allowed = this.pluck('pk');
        return _.each(ovivo.desktop.resources.groups.filter(function(group) {
          return group.parent() === null;
        }), function(group) {
          return _processGroup.call(_this, _allowed, null, group);
        });
      };
    })(),
    initialize: function(models, options) {
      _.extend(this, options);
      this.initResource();
      $.when(this.def, ovivo.desktop.resources.groups).then(_.bind(this.postProcess, this));
      return true;
    }
  }));
});
