// Generated by CoffeeScript 1.6.2
define(['models/resources/Inactivity', '_common/ResourceManagerBase', 'ovivo'], function(Model, ResourceManagerBase) {
  return Backbone.Collection.extend(_.extend({}, ResourceManagerBase, {
    model: Model,
    url: "" + ovivo.config.API_URL_PREFIX + "users/" + ovivo.config.USER_ID + "/inactivity/",
    comparator: function(inactivity) {
      return Date.parse(inactivity.start()).valueOf();
    },
    initialize: function() {
      this.initResource();
      return true;
    }
  }));
});
