// Generated by CoffeeScript 1.6.2
define(['models/resources/Period', '_common/ResourceManagerBase', 'ovivo'], function(Model, ResourceManagerBase) {
  return Backbone.Collection.extend(_.extend({}, ResourceManagerBase, {
    model: Model,
    fullResponse: true,
    localStorageOnly: true,
    url: "" + ovivo.config.API_URL_PREFIX + "resource-needs/periods/",
    initialize: function() {
      this.initResource();
      return true;
    }
  }));
});
