// Generated by CoffeeScript 1.6.2
define(['ovivo'], function() {
  return {
    compile: function(model, start, end, start_date, end_date, repeat, weekdaysHash) {
      var _arr, _day, _end, _i, _start, _startMonday, _startWeek;

      _arr = [];
      _start = new Date(Date.parse(start_date));
      _startWeek = _start.getWeek();
      _startMonday = new Date(_start);
      if (_startMonday.getDay() !== 1) {
        _startMonday.moveToDayOfWeek(1, -1);
      }
      _end = new Date(Date.parse(end_date));
      if (_start > start) {
        start = _start;
      }
      if ((_end != null) && (_end < end)) {
        end = _end;
      }
      _i = new Date(start);
      while (_i <= end) {
        _day = _i.getDay() - 1;
        if (_day < 0) {
          _day = 7 + _day;
        }
        if ((weekdaysHash[_day] === true) && ((repeat === 1) || (((Math.floor((_i - _startMonday) / 86400000 / 7)) % repeat) === 0))) {
          _arr.push({
            date: new Date(_i),
            model: model
          });
        }
        _i.setDate(_i.getDate() + 1);
      }
      return _arr;
    }
  };
});
