// Generated by CoffeeScript 1.6.2
define([], function() {
  var _animationEndGen;

  _animationEndGen = function(_def, enterClass, exitClass) {
    var _func;

    _func = function(e) {
      $(this).removeClass("" + enterClass + " " + exitClass + " transition back");
      _def.resolve();
      $(this).off('webkitAnimationEnd', _func);
      return true;
    };
    return _func;
  };
  return {
    transit: function(prev, next, enterClass, exitClass, reverse) {
      var _def, _defNext, _defPrev;

      _defNext = $.Deferred();
      _defPrev = $.Deferred();
      if (reverse === true) {
        $(next).css('z-index', 0);
        $(prev).css('z-index', 1);
      } else {
        $(next).css('z-index', 1);
        $(prev).css('z-index', 0);
      }
      if ((ovivo.config.PAGE_TRANSITION_ANIMATION === true) && (ovivo.config.ANIMATION_END !== false)) {
        $(next).on(ovivo.config.ANIMATION_END, _animationEndGen(_defNext, enterClass, exitClass));
        $(prev).on(ovivo.config.ANIMATION_END, _animationEndGen(_defPrev, enterClass, exitClass));
        if (reverse === true) {
          $(next).addClass('back');
          $(prev).addClass('back');
        }
        $(next).addClass(enterClass).addClass('transition');
        $(prev).addClass(exitClass).addClass('transition');
        return $.when(_defNext, _defPrev);
      } else {
        $(prev).addClass('hide');
        $(next).removeClass('hide');
        _def = new $.Deferred();
        _def.resolve();
        return _def;
      }
    }
  };
});
