// Generated by CoffeeScript 1.6.2
define(['ovivo'], function() {
  return {
    events: {},
    render: function() {
      return true;
    },
    addEvent: function(view) {
      this.events.push(view);
      this.calendarItems.append(view.el);
      this.updateEventsCounter();
      return true;
    },
    addWorkingHour: function(view) {
      return this.calendarItems.append(view.el);
    },
    updateEventsCounter: function() {
      var _html;

      _html = this.events.length > 1 ? this.events.length + ' ' + ngettext('event', 'events', this.events) : '';
      return this.eventsCounter.html(_html);
    },
    initialize: function() {
      this.proxyCall('initialize', arguments);
      this.events = [];
      this.calendarItems = this.$('.calendar-items');
      this.eventsCounter = this.$('.events-counter');
      return true;
    }
  };
});
