// Generated by CoffeeScript 1.6.2
define([], function() {
  return {
    addEvent: function(event) {
      var _group;

      if ((_group = this.periodGroups.get(event.group())) != null) {
        _group.addEvent(event);
      }
      return true;
    },
    removeEvent: function(event) {
      var _group;

      if ((_group = this.periodGroups.get(event.group())) != null) {
        _group.removeEvent(event);
      }
      return true;
    }
  };
});
