// Generated by CoffeeScript 1.6.2
define(['models/resources/ResourceBase', 'views/MonthDay', 'ovivo'], function(ResourceBase, View) {
  return ResourceBase.extend({
    _gettersNames: ['date', 'disabled', 'month', 'week_number', 'year'],
    addEvent: function(event) {
      return this.view.addEvent(event.view);
    },
    initialize: function(attrs, options) {
      this.proxyCall('initialize', arguments);
      this.set('pk', "" + (this.year()) + "-" + (this.month()) + "-" + (this.date()) + (this.disabled() === true ? '-disabled' : ''));
      this.view = new View({
        model: this,
        el: options.el
      });
      return true;
    }
  });
});
