// Generated by CoffeeScript 1.6.2
define(['_common/CalendarBase', 'models/resources/ResourceBase', 'views/Month', 'ovivo'], function(CalendarBase, ResourceBase, View) {
  return ResourceBase.extend(_.extend({}, CalendarBase, {
    firstDate: function() {
      return this._firstDate;
    },
    _gettersNames: ['month', 'year', 'pk'],
    show: function() {
      return this.view.show();
    },
    hide: function() {
      return this.view.hide();
    },
    initDays: function() {
      return this.collection.monthDays.initElements(this.view.dayElements, this.days);
    },
    initialize: function(attrs, options) {
      this.View = View;
      this.set('pk', "" + (this.year()) + "-" + (this.month()));
      this.on('rendered', this.initDays, this);
      this._firstDate = new Date(this.year(), this.month(), 1);
      this.weeks = this.getWeeksArr(this.year(), this.month());
      this.days = this.getDaysArr(this.weeks);
      this.proxyCall('initialize', arguments);
      ovivo.desktop.resources.events.fetchMonth(this.month(), this.year());
      return true;
    }
  }));
});
