// Generated by CoffeeScript 1.6.2
define(['views/PeriodBlock', 'models/resources/ResourceBase', 'ovivo'], function(View, ResourceBase) {
  return ResourceBase.extend({
    idAttribute: 'cid',
    _gettersNames: ['start_time', 'end_time', 'skill', 'employee_type', 'num_employees', 'date', 'model', 'groups', 'pk'],
    initialize: function() {
      this.View = View;
      this.proxyCall('initialize', arguments);
      return true;
    }
  });
});
