// Generated by CoffeeScript 1.6.2
define(['models/resources/ResourceBase', 'views/VoiceRecognition', 'ovivo'], function(ResourceBase, View) {
  return ResourceBase.extend({
    _gettersNames: ['processing', 'show'],
    changeProcessing: function() {
      var _val;

      _val = this.processing();
      if (_val === false) {
        this.set('show', false);
        return;
      }
      if (_val === true) {
        this._recognition.start();
      }
      return true;
    },
    processStart: function() {
      return console.log('started');
    },
    processEnd: function() {
      console.log('ended');
      return this.set('processing', false);
    },
    processResult: function(e) {
      return console.log('result:', e.originalEvent.results);
    },
    processError: function() {
      return console.log('error');
    },
    initialize: function() {
      if (window.webkitSpeechRecognition === void 0) {
        return;
      }
      this._recognition = new webkitSpeechRecognition();
      this._recognition.lang = ovivo.config.LANG;
      $(this._recognition).on('start', _.bind(this.processStart, this));
      $(this._recognition).on('end', _.bind(this.processEnd, this));
      $(this._recognition).on('result', _.bind(this.processResult, this));
      $(this._recognition).on('error', _.bind(this.processError, this));
      this.on('change:processing', this.changeProcessing, this);
      this.View = View;
      return this.proxyCall('initialize', arguments);
    }
  });
});
