// Generated by CoffeeScript 1.6.2
define(['ovivo'], function() {
  return Backbone.Collection.extend({
    _initialize: function() {
      this.initCacheProcessors();
      return true;
    }
  });
});
