// Generated by CoffeeScript 1.6.2
define(['models/period/Frame', 'ovivo'], function(Model) {
  return Backbone.Collection.extend({
    model: Model,
    doNotFetch: true,
    addFrame: function(start, end) {
      var _model;

      _model = new Model({
        start: start,
        end: end
      });
      this.add(_model);
      return _model;
    },
    processFrameAdd: function(frame) {
      return ovivo.desktop.resources.periods.def.done(function() {
        return ovivo.desktop.resources.periods.each(function(period) {
          return frame.addPeriod(period);
        });
      });
    },
    processPeriodAdd: function(period) {
      return this.each(function(frame) {
        return frame.addPeriod(period);
      });
    },
    processPeriodRemove: function(period) {
      return this.each(function(frame) {
        return frame.removePeriod(period);
      });
    },
    processPeriodChange: function(period) {
      return this.each(function(frame) {
        return frame.changePeriod(period);
      });
    },
    initialize: function() {
      this.on('add', this.processFrameAdd, this);
      ovivo.desktop.resources.periods.on('add', this.processPeriodAdd, this);
      ovivo.desktop.resources.periods.on('remove', this.processPeriodRemove, this);
      ovivo.desktop.resources.periods.on('updateFrames', this.processPeriodChange, this);
      return true;
    }
  });
});
