// Generated by CoffeeScript 1.6.2
define(['collections/period/Blocks', 'models/period/HoursBlock', '_common/CachableCollection', 'ovivo'], function(Blocks, Model, CachableCollection) {
  return Blocks.extend(_.extend({}, CachableCollection.get(['skills', 'groups', 'date']), {
    model: Model,
    initialize: function() {
      this._initialize();
      return true;
    }
  }));
});
