// Generated by CoffeeScript 1.6.2
define(['models/period/PeriodGroup', '_common/CachableCollection', 'ovivo'], function(Model, CachableCollection) {
  return Backbone.Collection.extend(_.extend({}, CachableCollection.get(['group']), {
    model: Model,
    addModel: function(obj) {
      var _model;

      _model = new Model(obj);
      this.add(_model);
      return _model;
    },
    getScrollData: function() {
      return [];
    },
    initialize: function() {
      this.initCacheProcessors();
      return true;
    }
  }));
});
