// Generated by CoffeeScript 1.6.2
define(['models/period/PeriodGroup', 'collections/period/GroupSectionsBase', '_common/CachableCollection', 'ovivo'], function(Model, GroupSectionsBase, CachableCollection) {
  return Backbone.Collection.extend(_.extend({}, GroupSectionsBase, CachableCollection.get(['root']), {
    model: Model,
    _itemsSelector: function() {
      return this.filter(function(m) {
        return m.visible() === true;
      });
    },
    initialize: function() {
      this.innerCollectionName = 'timeGroups';
      this.initCacheProcessors();
      return true;
    }
  }));
});
