// Generated by CoffeeScript 1.6.2
define(['models/period/PeriodGroup', 'collections/period/GroupSectionBase', 'ovivo'], function(Model, GroupSectionBase) {
  return Backbone.Collection.extend(_.extend({}, GroupSectionBase, {
    model: Model,
    initialize: function() {
      this.innerCollectionName = 'timeGroups';
      return true;
    }
  }));
});
