// Generated by CoffeeScript 1.6.2
define(['models/period/ResourceNeedTimeGroup', 'collections/period/GroupSectionBase', 'ovivo'], function(Model, GroupSectionBase) {
  return Backbone.Collection.extend(_.extend({}, GroupSectionBase, {
    model: Model,
    comparator: function(model) {
      return model.startValue();
    },
    initialize: function() {
      this.innerCollectionName = 'resourceNeedWeeks';
      return true;
    }
  }));
});
