// Generated by CoffeeScript 1.6.2
define(['models/period/ResourceNeedTimeGroup', '_features/binarySearch', 'ovivo'], function(Model, binarySearch) {
  return Backbone.Collection.extend(_.extend({}, {
    model: Model,
    addModel: function(obj) {
      var _model;

      _model = new Model(obj);
      this.add(_model);
      return _model;
    },
    comparator: function(model) {
      return model.startValue();
    },
    _scrollComparator: function(obj, val) {
      if (obj.start >= val) {
        return -1;
      }
      if (obj.end < val) {
        return 1;
      }
      return 0;
    },
    processScroll: function(val, height) {
      var _delta, _res;

      _res = binarySearch(this._scrollData, val, this._scrollComparator);
      if (_res !== null) {
        _delta = val - _res.start;
        _res.model.processScroll(_res, _delta);
        _res.model.resourceNeedWeeks.processScroll(_delta, height);
      }
      if (_res === this._prev) {
        return;
      }
      if (this._prev !== null) {
        this._prev.model.clearScroll();
      }
      return console.log(this._prev = _res);
    },
    calcScrollData: function() {
      if (this._prev != null) {
        this._prev.model.clearScroll();
      }
      this._prev = null;
      return this._scrollData = this.map(function(model) {
        var _h, _t;

        _h = model.view.el.offsetHeight;
        _t = model.view.el.offsetTop;
        model.resourceNeedWeeks.calcScrollData();
        return {
          el: model.view.el,
          model: model,
          start: _t,
          end: _t + _h,
          height: _h
        };
      });
    },
    initialize: function() {
      return true;
    }
  }));
});
