// Generated by CoffeeScript 1.6.2
define(['models/period/SkillGroup', 'collections/period/GroupSectionsBase', 'ovivo'], function(Model, GroupSectionsBase) {
  return Backbone.Collection.extend(_.extend({}, GroupSectionsBase, {
    model: Model,
    initialize: function() {
      return true;
    }
  }));
});
