// Generated by CoffeeScript 1.6.2
define(['models/resources/Event', 'ovivo'], function(Event) {
  var _Router;

  _Router = Backbone.Router.extend({
    routes: {},
    initialize: function() {
      return true;
    }
  });
  return new _Router();
});
