// Generated by CoffeeScript 1.6.2
define(['views/pages/PageBase', 'models/resources/Comment', 'ovivo'], function(PageBase, Comment) {
  return PageBase.extend({
    el: '.page.page-event-details',
    events: function() {
      return _.extend({}, PageBase.prototype.events, {
        'click .post-comment': 'postComment',
        'keyup .comment-input': 'keyCommentInput'
      });
    },
    headerTemplate: Handlebars.templates['eventDetailsHeader'],
    transitionStart: function() {
      this.proxyCall('transitionStart', arguments);
      return true;
    },
    transitionComplete: function() {
      this.proxyCall('transitionComplete', arguments);
      return true;
    },
    postComment: function() {
      var _comment, _commentText;

      _commentText = this.$('.comment-input').val();
      if (_commentText !== '') {
        _comment = new Comment({
          comment: _commentText,
          reply_to: null
        });
        this.model.get('event').comments.add(_comment);
        _comment.save();
        this.clearInput();
      }
      return true;
    },
    keyCommentInput: function() {
      if (this.$('.comment-input').val() !== '') {
        this.$('footer').addClass('active');
      } else {
        this.clearInput();
      }
      return true;
    },
    clearInput: function() {
      this.$('footer').removeClass('active');
      return this.$('.comment-input').val('');
    },
    renderComments: function() {
      var _comments;

      _comments = this.model.get('event').comments;
      _comments.each(function(comment) {
        return this.$('ul.comments').append(comment.view.el);
      });
      return true;
    },
    addComment: function(comment) {
      this.$('ul.comments').append(comment.view.el);
      return true;
    },
    syncEvent: function(event) {
      var _text;

      _text = event.has_applied() === true ? gettext('Your bid has now been received') : gettext('Your bid has been removed');
      return notificationMessage.post(this.el, _text);
    },
    changeEvent: function() {
      var _event, _eventDetailsView, _prevEvent,
        _this = this;

      this.clearInput();
      _event = this.model.get('event');
      _prevEvent = this.model.previous('event');
      _event.createDetailsView();
      _eventDetailsView = _event.detailsView;
      this.$('header span.title').html(this.headerTemplate(_eventDetailsView));
      this.$('.event-container').html('');
      this.$('.event-container').append(_eventDetailsView.el);
      _eventDetailsView.delegateEvents();
      _event.comments.on('add', this.addComment, this);
      _event.on('sync', this.syncEvent, this);
      if (_prevEvent != null) {
        _prevEvent.comments.off('add', this.addComment);
      }
      if (_prevEvent != null) {
        _prevEvent.off('sync', this.syncEvent);
      }
      _event.comments.def.done(function() {
        return _this.renderComments();
      });
      return true;
    },
    initialize: function() {
      this.proxyCall('initialize', arguments);
      this.model.on('change:event', this.changeEvent, this);
      return true;
    }
  });
});
