// Generated by CoffeeScript 1.6.2
define(['views/pages/PageBase', 'ovivo'], function(PageBase) {
  return PageBase.extend({
    el: '.page.page-resources .content-templates',
    name: 'templates',
    events: {
      'click .button-add-template': 'createTemplate'
    },
    highlight: function() {
      return this.$el.addClass('selected');
    },
    removeHighlight: function() {
      this.$el.removeClass('selected');
      return this.$('.selected').removeClass('selected');
    },
    createTemplate: function() {
      this.highlight();
      this.$('.button-add-template').addClass('selected');
      ovivo.desktop.pages.resources.view.showSubView('template');
      return ovivo.desktop.pages.resources.view.subViews.template.createNew();
    },
    addTemplate: function(model) {
      return this.$('ul.templates').append(model.view.el);
    },
    initialize: function() {
      ovivo.desktop.resources.templates.on('add', this.addTemplate, this);
      return true;
    }
  });
});
