// Generated by CoffeeScript 1.6.2
define(['views/pages/PageBase', '_common/ResourceEditCommon', 'ovivo'], function(PageBase, ResourceEditCommon) {
  var _resourceEditCommon;

  _resourceEditCommon = ResourceEditCommon.get({});
  return PageBase.extend(_.extend({}, _resourceEditCommon, {
    el: '.page.page-resources .content-template',
    name: 'template',
    events: _.extend({}, _resourceEditCommon.events, {}),
    fields: ['name', 'repeat', 'resource_needs', 'primary_department'],
    primaryDepartmentsTemplate: Handlebars.templates['primaryDepartments'],
    resourceNeedsTemplate: Handlebars.templates['resourceNeeds'],
    primaryDepartments: function() {
      return _.compact(_.map(ovivo.desktop.resources.groups.tree, function(elem) {
        if (elem.groups.length > 0) {
          return elem.pd;
        } else {
          return void 0;
        }
      }));
    },
    resourceNeeds: function() {
      return ovivo.desktop.resources.resourceNeeds.map(function(model) {
        return model;
      });
    },
    resourceNeedsProcessor: function(value) {
      return _.map(value, function(resourceNeed) {
        return parseInt(resourceNeed);
      });
    },
    types: function() {
      return {
        'name': String,
        'repeat': Number,
        'resource_needs': this.resourceNeedsProcessor,
        'primary_department': Number
      };
    },
    initCreateMode: function() {
      _resourceEditCommon.initCreateMode.call(this);
      this.page.showElements('template', '.create-mode');
      return this.page.hideElements('template', '.edit-mode');
    },
    initEditMode: function() {
      _resourceEditCommon.initEditMode.call(this);
      this.page.showElements('template', '.edit-mode');
      return this.page.hideElements('template', '.create-mode');
    },
    createNew: function() {
      var _ref;

      this.setModel(new this.collection.model({
        name: '',
        repeat: 1,
        resource_needs: [],
        primary_department: (_ref = ovivo.desktop.resources.primaryDepartments.at(0)) != null ? _ref.pk() : void 0
      }));
      return this.initCreateMode();
    },
    processResourceNeeds: function() {
      var _select;

      _select = this.$('.property-value-resource_needs');
      _select.children().remove();
      return _select.append($(this.resourceNeedsTemplate(this)).children());
    },
    processPD: function() {
      return this.$('.property-value-primary_department').append($(this.primaryDepartmentsTemplate(this)).children());
    },
    close: function() {
      this.page.showSubView('periods');
      return this.page.subViews.templates.removeHighlight();
    },
    initialize: function() {
      var _resourceNeedsProcessor,
        _this = this;

      this.types = this.types();
      this.collection = ovivo.desktop.resources.templates;
      _resourceNeedsProcessor = _.bind(this.processResourceNeeds, this);
      this.on('action:add', this.add, this);
      this.on('action:delete', this["delete"], this);
      ovivo.desktop.resources.resourceNeeds.def.done(_resourceNeedsProcessor);
      ovivo.desktop.resources.groups.on('tree-ready', this.processPD, this);
      ovivo.desktop.resources.resourceNeeds.def.done(function() {
        ovivo.desktop.resources.resourceNeeds.on('add', _resourceNeedsProcessor);
        ovivo.desktop.resources.resourceNeeds.on('change', _resourceNeedsProcessor);
        return ovivo.desktop.resources.resourceNeeds.on('remove', _resourceNeedsProcessor);
      });
      return true;
    }
  }));
});
