// Generated by CoffeeScript 1.6.2
define(['views/pages/PageBase', 'ovivo'], function(PageBase) {
  return PageBase.extend({
    el: '.page.page-resources .content-timeline',
    name: 'timeline',
    events: {},
    close: function() {
      return this.page.showSubView('periods');
    },
    initialize: function() {
      return true;
    }
  });
});
