// Generated by CoffeeScript 1.6.2
define(['models/MonthDay', 'ovivo'], function(Model) {
  return Backbone.Collection.extend({
    model: Model,
    initElements: function(elements, days) {
      var _this = this;

      return _.each(_.zip(elements, days), function(_arg) {
        var day, element;

        element = _arg[0], day = _arg[1];
        _this.add(day, {
          el: element
        });
        return _this;
      });
    },
    processEventAdd: function(event) {
      var _ref;

      return (_ref = this.get(event.getKey())) != null ? _ref.addEvent(event) : void 0;
    },
    initialize: function(models, options) {
      _.extend(this, options);
      ovivo.desktop.resources.events.on('add', this.processEventAdd, this);
      return true;
    }
  });
});
