// Generated by CoffeeScript 1.6.2
define(['models/Month', 'collections/MonthDays', 'ovivo'], function(Model, MonthDays) {
  return Backbone.Collection.extend({
    model: Model,
    comparator: function(month) {
      return month.firstDate();
    },
    addMonth: function(obj) {
      var _month;

      _month = new Model(obj, {
        collection: this
      });
      this.add(_month);
      return _month;
    },
    show: function(month) {
      if (this.prevMonth != null) {
        this.prevMonth.hide();
        this.trigger('hide', this.prevMonth);
      }
      month.show();
      this.trigger('show', month);
      return this.prevMonth = month;
    },
    prev: function() {
      var _first, _prev;

      _first = this.first();
      _prev = new Date(_first.year(), _first.month() - 1, 1);
      return this.add({
        month: _prev.getMonth(),
        year: _prev.getFullYear()
      });
    },
    next: function() {
      var _last, _next;

      _last = this.last();
      _next = new Date(_last.year(), _last.month() + 1, 1);
      return this.add({
        month: _next.getMonth(),
        year: _next.getFullYear()
      });
    },
    initialize: function(models, options) {
      ovivo.desktop.monthDays = this.monthDays = new MonthDays();
      _.extend(this, options);
      return true;
    }
  });
});
