// Generated by CoffeeScript 1.6.2
define(['models/PeriodBlock', '_common/CachableCollection', 'ovivo'], function(Model, CachableCollection) {
  var _PeriodBlocks;

  _PeriodBlocks = Backbone.Collection.extend(_.extend({}, CachableCollection.get(['skill']), {
    model: Model,
    initialize: function() {
      this.initCacheProcessors();
      return true;
    }
  }));
  _PeriodBlocks.create = function(data) {
    var _blocks, _models;

    _models = _.map(data, function(obj) {
      return _.extend(obj, {
        start_time: obj.model.start_time(),
        end_time: obj.model.end_time(),
        skill: obj.model.skill(),
        employee_type: obj.model.skill(),
        num_employees: obj.model.num_employees(),
        pk: obj.model.pk()
      });
    });
    _blocks = new _PeriodBlocks();
    _blocks.add(_models);
    return _blocks;
  };
  return _PeriodBlocks;
});
