// Generated by CoffeeScript 1.6.2
define(['_common/ToolsBase', 'ovivo'], function(ToolsBase) {
  var _Base;

  _Base = Backbone.Model.extend(_.extend({}, ToolsBase, {
    show: function() {
      return this.view.show.apply(this.view, Array.prototype.slice.call(arguments, 0));
    },
    initialize: function(attrs, options) {
      var _obj;

      _obj = {
        model: this
      };
      if ((options != null ? options.el : void 0) != null) {
        _obj.el = options.el;
      }
      this.view = new this.View(_obj);
      return true;
    },
    clear: function() {
      if (this.view.clear != null) {
        return this.view.clear();
      }
    }
  }));
  _Base.prototype._base = _Base;
  return _Base;
});
